apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      containers:
        - name: jellyseerr
          image: fallenbagel/jellyseerr:latest
          ports:
            - containerPort: 5055
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: PORT
              value: "5055"
            - name: JELLYFIN_TYPE
              value: "emby"
            # jellyfin setup
            - name: JELLYFIN_HOST
              value: "http://jellyfin-service.media.svc.cluster.local:8096"
            - name: JELLYFIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: jellyseerr-secrets
                  key: jellyfin-api-key
            # sonarr setup
            - name: SONARR_HOST
              value: "http://sonarr-service.media.svc.cluster.local:8989"
            - name: SONARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: jellyseerr-secrets
                  key: sonarr-api-key
            # radarr setup
            - name: RADARR_HOST
              value: "http://radarr-service.media.svc.cluster.local:7878"
            - name: RADARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: jellyseerr-secrets
                  key: radarr-api-key
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyseerr-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr-service
  namespace: media
spec:
  selector:
    app: jellyseerr
  ports:
    - name: http
      port: 5055
      targetPort: 5055
      nodePort: 30008
  type: NodePort
