apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: media-ingress
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/jellyfin`)
      kind: Rule
      services:
        - name: jellyfin-service
          port: 8096
      middlewares:
        - name: jellyfin-stripprefix
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: jellyfin-stripprefix
  namespace: media
spec:
  stripPrefix:
    prefixes:
      - "/jellyfin"
