apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: transmission
          image: lscr.io/linuxserver/transmission:latest
          ports:
            - containerPort: 9091 # Web UI
            - containerPort: 51413 # Torrent port (now binds to host)
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
            - name: USER
              value: "admin"
            - name: PASS
              value: "password"
            - name: PEERPORT
              value: "51413" # Explicitly set the torrent port
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: watch
              mountPath: /watch
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: transmission-config-pvc
        - name: downloads
          hostPath:
            path: /media/HDD/downloads
        - name: watch
          hostPath:
            path: /media/HDD/watch
---
apiVersion: v1
kind: Service
metadata:
  name: transmission-service
  namespace: media
spec:
  selector:
    app: transmission
  ports:
    - name: web
      port: 9091
      targetPort: 9091
      nodePort: 30004
  type: NodePort
